import React from 'react';
import type { Metadata } from 'next';
import { Teko } from 'next/font/google';
import { getAssetPath } from '@/utils/paths';
import './globals.css';
import CartProvider from './Carrinho/cart';
import FavoritesProvider from './Favoritos/favorites';

// Log para diagnosticar carregamento do RootLayout
console.log('🎯 RootLayout: Layout principal carregado');

const teko = Teko({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-teko',
});

export const metadata: Metadata = {
  title: 'Ideal Uniformes | Equipamentos Militares ',
  description: 'Generated by create next app',
  icons: {
    icon: getAssetPath('/logo-ideal.svg'),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={teko.variable}>
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            console.log('🎯 RootLayout: HTML carregado');
            window.addEventListener('DOMContentLoaded', function() {
              console.log('🎯 DOMContentLoaded: Verificando CSS');
              const rootStyles = getComputedStyle(document.documentElement);
              const cssLoaded = rootStyles.getPropertyValue('--debug-css-loaded');
              console.log('🎯 CSS Global carregado:', cssLoaded ? 'SIM' : 'NÃO');
              
              // Verificar se estilos dos módulos estão aplicados
              setTimeout(() => {
                const headerEl = document.querySelector('[data-name="main-header"]');
                const footerEl = document.querySelector('[data-name="main-footer"]');
                if (headerEl) {
                  console.log('🎯 Header styles:', getComputedStyle(headerEl));
                }
                if (footerEl) {
                  console.log('🎯 Footer styles:', getComputedStyle(footerEl));
                }
              }, 1000);
            });
          `
        }} />
      </head>
      <body className="antialiased">
        <React.Suspense fallback={null}>
          <CartProvider>
            <FavoritesProvider>
              {children}
            </FavoritesProvider>
          </CartProvider>
        </React.Suspense>
      </body>
    </html>
  );
}
